# Generated by Django 4.0.4 on 2022-05-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_contact_details',
            name='company_location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person_contact_details',
            name='company_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
